"""The identity gate — Stage 7 Phase A.

§7.5 of the parent architecture closes with *"a signature-stability test asserts
that no `ProblemID`/`ModelID` changes as a result of the refactor (a silent
identity change would orphan the entire store)"*. **There was no such test.**
Every identifier assertion in the suite is either an arbitrary literal
(`ModelID("0123456789abcdef")` — 50 of them across 8 files) or a self-comparison
(`a.problem_id == b.problem_id`), and both are invariant under a *uniform* shift:
a refactor that moved every signature tree identically would orphan all 162
stored models and pass green.

The only thing that could see such a shift was `tools/probes/identity_probe.py`,
a cross-branch diff run by hand, outside `pytest`, that a merge can forget. This
module is that probe made unforgettable: the surface is frozen as a committed
golden and compared on every run.

**The golden is never regenerated by the test.** A golden that rewrites itself on
failure is a test that cannot fail — the same defect class the paragraph above
describes, one level up. Re-baselining is a deliberate manual command with no
flag and no environment variable, and `test_this_module_cannot_write_the_golden`
asserts statically that no path through this file can perform it.
"""

from __future__ import annotations

import ast
import importlib
import importlib.util
import inspect
import re
from collections.abc import Iterator, Sequence
from contextlib import contextmanager
from pathlib import Path
from types import ModuleType
from typing import Any

import pytest

REPO = Path(__file__).resolve().parents[2]
SRC = REPO / "src" / "mbl"
PROBE = REPO / "tools" / "probes" / "identity_probe.py"
GOLDEN = Path(__file__).parent / "fixtures" / "identity_surface.txt"

#: The one way to move the golden. No `--force`, no `--update-golden`, no
#: environment variable: re-baselining is a decision, and a decision has to be
#: taken by a person who then has to look at the diff.
REBASELINE = (
    "uv run python tools/probes/identity_probe.py "
    "> tests/architecture/fixtures/identity_surface.txt"
)

#: What one moved line costs, stated in the failure rather than left to be
#: recalled: the store holds 162 models and 162 measurements filed under these
#: identifiers, and a record whose identifier moved is a record `mbl run` cannot
#: find and will therefore train again.
ORPHAN_WARNING = (
    "every model and measurement filed under an identifier on the left is "
    "ORPHANED: nothing resolves to it, and the next run retrains it"
)

#: Classes that define `get_signature` and are **deliberately outside** the
#: gate, each with the reason it contributes no byte to any stored identifier.
#: This is a list of *exclusions*, never of today's families: a new signable
#: class fails `test_every_signable_class_is_accounted_for` until someone
#: decides which side of the gate it is on.
_INTERFACE = (
    "the interface, not an implementation: `get_signature` here is a Protocol "
    "declaration or an abstract default, and what a stored identifier signs is "
    "a concrete class"
)
_BUILT_OBJECT = (
    "a BUILT object, reached only through `compute_run_signature` — the "
    "parallel digest over live objects that `ProblemSignatureCallback` computes "
    "on every training and that no stored identifier reads (Stage 7 §3.2)"
)
_SYNTHESIS_ONLY = (
    "reached only by an actual synthesis; what it signs lands in the artifact's "
    "own provenance, while `spec.json`'s `synthesizer` key is the CONTENDER's "
    "signature (`producer._synthesizer_signature`)"
)
_PHASE_D = "identity-bearing from Stage 6 Phase D; add a probe line then"
_NOT_YET_A_DOCUMENT = (
    "an application-layer type of a study that is not yet expressed as a "
    "document; it enters an identifier only through the two types above, which "
    "carry the Phase D reason"
)
_LEGACY = (
    "the pre-Stage-2 surface, on Stage 6 Phase E's deletion ledger; its digest "
    "is pinned separately by the probe's `legacy.*` lines"
)

NOT_IN_THE_GATE: dict[str, str] = {
    # -- the interface itself -------------------------------------------------
    "applications/factories.py::BatchSpec": _INTERFACE,
    "applications/factories.py::ProblemFactory": _INTERFACE,
    "core/constraint/constraint.py::Constraint": _INTERFACE,
    "core/cost/cost.py::Cost": _INTERFACE,
    "core/system/system.py::System": _INTERFACE,
    "core/utils/signing.py::Signable": _INTERFACE,
    "models/base.py::Controller": _INTERFACE,
    "models/iterative/initializers.py::ControlInitializer": _INTERFACE,
    "models/iterative/refinement.py::GradientDescentRefinement": _INTERFACE,
    "models/iterative/refinement.py::IterativeRefinement": _INTERFACE,
    "models/iterative/sweeps.py::SweepStrategy": _INTERFACE,
    "models/lifecycle.py::SynthesizedController": _INTERFACE,
    "models/lifecycle.py::Synthesizer": _INTERFACE,
    "models/lifecycle.py::SynthesizerBase": _INTERFACE,
    "models/samplers.py::Distribution": _INTERFACE,
    "models/unfolded/parameters.py::UnfoldedParameter": _INTERFACE,
    "spec/contender.py::Recipe": _INTERFACE,
    # -- built objects: the second, parallel identity mechanism ---------------
    "core/constraint/box_constraint.py::BoxConstraint": (
        f"{_BUILT_OBJECT}. `ProblemData` signs `control_bound` itself, so the "
        "box a study declares is in `ProblemID` without this class"
    ),
    "core/cost/quadratic_cost.py::QuadraticCost": _BUILT_OBJECT,
    "core/optimal_control_problem.py::OptimalControlProblem": _BUILT_OBJECT,
    "core/system/linear_system.py::LinearSystem": _BUILT_OBJECT,
    "core/system/state_space_system.py::StateSpaceSystem": _BUILT_OBJECT,
    "models/analytic/iterative_gd.py::AnalyticalIterativeGDController": _BUILT_OBJECT,
    "models/analytic/riccati.py::RiccatiController": _BUILT_OBJECT,
    "models/analytic/riccati.py::SynthesizedRiccatiController": _BUILT_OBJECT,
    "models/analytic/truncated_riccati.py::TruncatedRiccatiController": _BUILT_OBJECT,
    "models/analytic/truncated_riccati.py::SynthesizedTruncatedRiccatiController": (
        _BUILT_OBJECT
    ),
    "models/constrained/cocp.py::COCPController": _BUILT_OBJECT,
    "models/constrained/cocp_exact.py::ExactCOCPController": _BUILT_OBJECT,
    "models/neural/nerual.py::NeuralPolicy": _BUILT_OBJECT,
    "models/open_loop/gd_controller.py::OpenLoopGDController": _BUILT_OBJECT,
    "models/unfolded/base.py::UnfoldedController": _BUILT_OBJECT,
    "models/unfolded/layerwise.py::ParameterActivation": _BUILT_OBJECT,
    "models/iterative/initializers.py::ConstantInitializer": (
        f"{_BUILT_OBJECT}. What a study declares is `init_method` -- a string "
        "field of the recipe, and signed as one; the initializer is built from "
        "it at execution time"
    ),
    "models/iterative/initializers.py::SamplerInitializer": (
        f"{_BUILT_OBJECT}. Built from the declared `init_method`, as above"
    ),
    "models/iterative/initializers.py::WarmStartInitializer": (
        f"{_BUILT_OBJECT}. Built from the declared `init_method`, as above"
    ),
    "models/samplers.py::ConstantDistribution": _BUILT_OBJECT,
    "models/samplers.py::NumpyGaussianDistribution": _BUILT_OBJECT,
    "models/samplers.py::RandomSampler": _BUILT_OBJECT,
    "models/samplers.py::TorchGaussianDistribution": _BUILT_OBJECT,
    "models/samplers.py::TorchZeroDistribution": _BUILT_OBJECT,
    "models/samplers.py::ZeroDistribution": _BUILT_OBJECT,
    "models/constrained/solver_spec.py::COCPSolverSpec": (
        "D17 signs the solver backend as the NAME the contender declares "
        "(`COCPRecipe.solver_backend`, a string field of the recipe); this spec "
        "is built from that name at execution time and signs nothing stored"
    ),
    # -- reached only by a real synthesis -------------------------------------
    "applications/recipes/base.py::EngineTrainedSynthesizer": _SYNTHESIS_ONLY,
    "applications/recipes/base.py::FrozenControllerSynthesizer": _SYNTHESIS_ONLY,
    "applications/recipes/base.py::TrainedControllerArtifact": _SYNTHESIS_ONLY,
    "applications/recipes/unfolded.py::WarmStartSynthesizer": _SYNTHESIS_ONLY,
    "models/analytic/riccati.py::RiccatiSynthesizer": _SYNTHESIS_ONLY,
    "models/analytic/truncated_riccati.py::TruncatedRiccatiSynthesizer": (
        _SYNTHESIS_ONLY
    ),
    # -- identity-bearing in waiting (Stage 6 Phase D) ------------------------
    "applications/ood/noise.py::ExoticBatchSpec": f"{_PHASE_D} (NB06)",
    "applications/uncertainty/noise.py::ExoticBatchSpec": f"{_PHASE_D} (NB07)",
    "applications/ltv_factories.py::LTVLQRProblemFactory": f"{_PHASE_D} (NB05)",
    "applications/ood/perturbations.py::PerturbedLQRProblemFactory": (
        f"{_PHASE_D} (NB06/NB07)"
    ),
    # -- their helpers, which enter only through the four above ---------------
    "applications/ood/constraint_shift.py::ControlBoundShift": _NOT_YET_A_DOCUMENT,
    "applications/ood/noise.py::_ExoticNumpyDistribution": _NOT_YET_A_DOCUMENT,
    "applications/ood/perturbations.py::DynamicsPerturbation": _NOT_YET_A_DOCUMENT,
    "applications/uncertainty/dataset.py::FiniteTrajectoryDatasetSpec": (
        _NOT_YET_A_DOCUMENT
    ),
    "applications/uncertainty/distances.py::DistributionDistance": _NOT_YET_A_DOCUMENT,
    "applications/uncertainty/noise.py::NumpyCauchyDistribution": _NOT_YET_A_DOCUMENT,
    "applications/uncertainty/noise.py::NumpyLaplaceDistribution": _NOT_YET_A_DOCUMENT,
    "applications/uncertainty/noise.py::NumpyUniformDistribution": _NOT_YET_A_DOCUMENT,
    "applications/uncertainty/noise.py::TorchCauchyDistribution": _NOT_YET_A_DOCUMENT,
    "applications/uncertainty/noise.py::TorchLaplaceDistribution": _NOT_YET_A_DOCUMENT,
    "applications/uncertainty/noise.py::TorchUniformDistribution": _NOT_YET_A_DOCUMENT,
    "applications/uncertainty/perturbations.py::PerturbationDistribution": (
        _NOT_YET_A_DOCUMENT
    ),
    "applications/uncertainty/perturbations.py::PlantPerturbation": _NOT_YET_A_DOCUMENT,
    # -- the surface Stage 2 replaced -----------------------------------------
    "applications/case_study.py::CaseStudy": _LEGACY,
    "experiments/experiment.py::Experiment": _LEGACY,
}


# --------------------------------------------------------------------------
# The probe, the golden, and the report
# --------------------------------------------------------------------------


def _load_probe() -> ModuleType:
    """Import the probe by path. `tools/` is not a package, deliberately: it is
    run as a script against two worktrees at once."""
    spec = importlib.util.spec_from_file_location("identity_probe", PROBE)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="module")
def probe() -> ModuleType:
    return _load_probe()


@pytest.fixture(scope="module")
def surface(probe: ModuleType) -> list[str]:
    return list(probe.surface_lines())


def read_golden(path: Path = GOLDEN) -> list[str]:
    """The committed surface.

    A missing fixture is a *decision that was not taken*, not an I/O error, so
    it says what to do about it. `FileNotFoundError` from a test whose subject
    is a golden file tells the reader nothing they did not already see.
    """
    if not path.is_file():
        raise AssertionError(
            f"the identity golden is missing at {path}. It is committed, never "
            f"generated by the suite; create it deliberately with:\n    {REBASELINE}"
        )
    return path.read_text(encoding="utf-8").splitlines()


def _labelled(lines: Sequence[str]) -> dict[str, str]:
    """`label value` -> `{label: value}`, in order."""
    labelled: dict[str, str] = {}
    for text in lines:
        label, _, value = text.partition(" ")
        labelled[label] = value
    return labelled


def report(golden: Sequence[str], current: Sequence[str]) -> str:
    """What moved, or `""` when nothing did.

    A bare `assert a == b` over 73 lines is unreadable at the moment it matters
    most — pytest prints two walls of hexadecimal and the reader has to find the
    changed one. This names each moved label, and says what a moved label costs.
    """
    if list(golden) == list(current):
        return ""
    was, now = _labelled(golden), _labelled(current)
    moved = [(k, was[k], now[k]) for k in was if k in now and was[k] != now[k]]
    gone = [k for k in was if k not in now]
    fresh = [k for k in now if k not in was]

    lines = ["THE IDENTITY SURFACE MOVED."]
    if moved:
        lines += ["", f"{len(moved)} identifier(s) changed:"]
        lines += [f"  moved {label}: {old} → {new}" for label, old, new in moved]
        lines += ["", ORPHAN_WARNING + "."]
    if gone:
        lines += ["", "no longer produced:"] + [f"  gone {label}" for label in gone]
    if fresh:
        lines += ["", "newly produced:"] + [f"  added {label}" for label in fresh]
    lines += [
        "",
        "If this change is deliberate, re-baseline BY HAND after reading the "
        "diff above:",
        f"    {REBASELINE}",
    ]
    return "\n".join(lines)


# --------------------------------------------------------------------------
# The gate
# --------------------------------------------------------------------------


def test_identity_surface_is_unchanged(surface: list[str]) -> None:
    """The gate §7.5 assumed already existed."""
    problems = report(read_golden(), surface)
    if problems:
        pytest.fail(problems)


def test_the_surface_is_a_pure_function_of_the_source_tree(
    probe: ModuleType,
    surface: list[str],
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """From another working directory, with `MBL_STORE` unset.

    The probe's whole value is that two checkouts can be compared; a surface
    that depended on where it ran, or on a store that happened to be present,
    would make a diff mean nothing. This is also the single-specimen trap that
    already struck once in this project: every check that had ever executed the
    notebook set `MBL_STORE`, so none exercised the bare case.

    **It re-asserts the golden too, and that overlap is deliberate.** Found by
    mutation: disabling the report path in `test_identity_surface_is_unchanged`
    left the suite green when only this test still compared anything. One test
    owns the readable refusal; this one owns the hostile environment; both
    compare, so neither is the single point at which the gate can be switched
    off by editing one line.
    """
    monkeypatch.delenv("MBL_STORE", raising=False)
    monkeypatch.chdir(tmp_path)

    assert probe.surface_lines() == surface
    assert probe.surface_lines() == read_golden()


def test_the_surface_is_stable_across_two_calls(probe: ModuleType) -> None:
    """Byte-identical twice, so a diff between branches is about the branches."""
    assert probe.surface_lines() == probe.surface_lines()


# --------------------------------------------------------------------------
# The refusal is a deliverable of its own
# --------------------------------------------------------------------------


def test_the_failure_names_every_moved_label_and_what_it_costs() -> None:
    """Parsed out of the message, never `"seed" in message`.

    A substring that appears anyway is this project's most repeated test defect
    — five occurrences now — and a failure message is exactly the kind of text
    in which any given word appears somewhere.
    """
    golden = ["a.model_id 1111", "b.model_id 2222", "c.points 27"]
    current = ["a.model_id 9999", "b.model_id 2222", "c.points 28"]

    message = report(golden, current)

    moved = dict(
        (match.group(1), (match.group(2), match.group(3)))
        for match in re.finditer(r"^  moved (\S+): (\S+) → (\S+)$", message, re.M)
    )
    assert moved == {"a.model_id": ("1111", "9999"), "c.points": ("27", "28")}
    assert ORPHAN_WARNING in message
    assert REBASELINE in message


def test_the_failure_names_a_label_that_disappeared() -> None:
    """A probe line deleted is a hole in the gate, and reads as no change at all
    unless the message says otherwise."""
    message = report(["a.model_id 1111", "b.model_id 2222"], ["a.model_id 1111"])

    assert re.findall(r"^  gone (\S+)$", message, re.M) == ["b.model_id"]


def test_an_unchanged_surface_reports_nothing() -> None:
    """The report is capable of saying nothing, which is what makes the
    assertions above statements about a real mismatch."""
    assert report(["a 1", "b 2"], ["a 1", "b 2"]) == ""


def test_a_missing_golden_asks_for_a_deliberate_rebaseline(tmp_path: Path) -> None:
    with pytest.raises(AssertionError) as failure:
        read_golden(tmp_path / "identity_surface.txt")

    assert REBASELINE in str(failure.value)


def test_this_module_cannot_write_the_golden() -> None:
    """Statically, in the style `test_boundaries.py` already uses.

    A convenience flag added later — `--update-golden`, an environment variable,
    a `write_text` in a fixture — fails this test rather than silently disarming
    the gate.
    """
    tree = ast.parse(Path(__file__).read_text(encoding="utf-8"))
    writes = [
        node
        for node in ast.walk(tree)
        if isinstance(node, ast.Call)
        and (
            (isinstance(node.func, ast.Name) and node.func.id == "open")
            or (
                isinstance(node.func, ast.Attribute)
                and node.func.attr
                in {"open", "write", "write_text", "write_bytes", "writelines"}
            )
        )
    ]
    assert not writes, (
        "this module can write; the golden must only ever be re-baselined by "
        f"hand:\n    {REBASELINE}"
    )


# --------------------------------------------------------------------------
# Coverage: nothing signable is unaccounted for
# --------------------------------------------------------------------------


def _class_definitions(tree: ast.AST, prefix: str = "") -> list[str]:
    """Qualified names of every class in `tree` that DEFINES `get_signature`."""
    found: list[str] = []
    for node in ast.iter_child_nodes(tree):
        if not isinstance(node, ast.ClassDef):
            continue
        qualname = f"{prefix}{node.name}"
        if any(
            isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef))
            and child.name == "get_signature"
            for child in node.body
        ):
            found.append(qualname)
        found.extend(_class_definitions(node, f"{qualname}."))
    return found


def discover_signables() -> dict[str, str]:
    """`path::QualName` -> importable module name, for every signable class.

    **The filesystem, never `pkgutil`.** A discovery that walks imported
    packages sees what the interpreter happened to import, which on a partially
    imported tree is a subset that shrinks silently — and a coverage test whose
    denominator can shrink is a coverage test that can be satisfied by breaking
    an import.
    """
    discovered: dict[str, str] = {}
    for path in sorted(SRC.rglob("*.py")):
        tree = ast.parse(path.read_text(encoding="utf-8"))
        relative = path.relative_to(SRC)
        parts = [part for part in relative.with_suffix("").parts if part != "__init__"]
        module = ".".join(["mbl", *parts])
        for qualname in _class_definitions(tree):
            discovered[f"{relative.as_posix()}::{qualname}"] = module
    return discovered


def _resolve(module_name: str, qualname: str) -> Any:
    obj: Any = importlib.import_module(module_name)
    for part in qualname.split("."):
        obj = getattr(obj, part)
    return obj


@contextmanager
def recording() -> Iterator[set[str]]:
    """Wrap `get_signature` on every discovered class and record what is called.

    The covered set is **derived, never carried**: two hand-maintained lists
    would drift against each other and against the probe, and the drift would
    read as coverage.

    A patched `get_signature` left on a live class leaks into every test that
    runs after this one in the same session, so the restore is in `finally` and
    `test_the_recorder_leaves_every_class_as_it_found_it` checks it *after* the
    block has exited — which is the only place the check means anything.
    """
    seen: set[str] = set()
    restore: list[tuple[Any, Any]] = []
    for key, module_name in discover_signables().items():
        owner = _resolve(module_name, key.split("::", 1)[1])
        original = owner.__dict__.get("get_signature")
        if not inspect.isfunction(original):  # inherited, or not a plain method
            continue

        def recorder(
            self: Any, *args: Any, _key: str = key, _original: Any = original, **kw: Any
        ) -> Any:
            seen.add(_key)
            return _original(self, *args, **kw)

        setattr(owner, "get_signature", recorder)
        restore.append((owner, original))
    try:
        yield seen
    finally:
        for owner, original in restore:
            setattr(owner, "get_signature", original)


@pytest.fixture
def reached(probe: ModuleType) -> Iterator[set[str]]:
    """Which signable classes one call of the probe actually exercises."""
    with recording() as seen:
        probe.surface_lines()
        yield seen


def test_every_signable_class_is_accounted_for(reached: set[str]) -> None:
    """Either the probe reaches it, or `NOT_IN_THE_GATE` says why it need not.

    This is the mechanism that needs no enumeration of today's families: a new
    signable class fails here until someone decides which side of the gate it is
    on. It is the standing rule against designing around a free parameter's
    current value, applied to the gate itself.
    """
    unaccounted = set(discover_signables()) - reached - set(NOT_IN_THE_GATE)
    assert not unaccounted, (
        "these classes define `get_signature`, are not reached by the identity "
        "probe, and are not excluded from it:\n  "
        + "\n  ".join(sorted(unaccounted))
        + "\n\nDecide which they are: add a probe line if the class can reach a "
        "stored identifier, or an entry in NOT_IN_THE_GATE with the reason it "
        "cannot."
    )


def test_no_exclusion_outlives_its_class() -> None:
    """An exclusion for a class that no longer exists is a comment pretending to
    be a decision, and it hides the day the class comes back under a new name."""
    stale = set(NOT_IN_THE_GATE) - set(discover_signables())
    assert not stale, (
        "NOT_IN_THE_GATE names classes that no longer define `get_signature`:\n  "
        + "\n  ".join(sorted(stale))
    )


def test_every_exclusion_carries_a_reason() -> None:
    reasonless = [key for key, reason in NOT_IN_THE_GATE.items() if len(reason) < 40]
    assert not reasonless, (
        "an exclusion without a reason is an exclusion nobody can review:\n  "
        + "\n  ".join(sorted(reasonless))
    )


def test_the_recorder_leaves_every_class_as_it_found_it(probe: ModuleType) -> None:
    """The companion assertion to `recording`'s `finally`, taken **after** the
    block exits — inside it, the recorder is supposed to be installed.

    Checked on a class the probe genuinely reaches and against the original
    function object, not against its name: a wrapper that copied `__name__`
    through `functools.wraps` would pass a name comparison while still being
    the wrapper.
    """
    problem_spec = _resolve("mbl.spec.problem", "ProblemSpec")
    before = problem_spec.__dict__["get_signature"]

    with recording() as seen:
        probe.surface_lines()
        assert problem_spec.__dict__["get_signature"] is not before, (
            "the recorder never wrapped a class the probe reaches, so this "
            "test would pass without restoring anything"
        )

    assert seen, "the recorder must have recorded something to be meaningful"
    assert problem_spec.__dict__["get_signature"] is before
