"""Does the projected-gradient baseline's plateau depend on its step size?

A standing probe rather than a test: it runs the real fixed-step recipe on the
real frozen plant across a depth axis, and answers the question a reviewer asks
first -- *did you try a smaller step?*

The baseline in the ICASSP campaign's two large-instance figures declares
``2/L``. At the binding box that curve does almost all of its descent in three
iterations and then stops far above the exact convex optimum, which reads as a
method that is not converging. The natural suspicion is that ``2/L`` sits at
the stability boundary, where the highest-curvature mode's contraction factor
is exactly one.

**Measured, and the suspicion is wrong.** At ``u_max = 0.02``, J = 1..10::

    J      2/L        1/L       1/2L
    1   133.6447   135.0259   141.5498
    3   132.9953   133.1238   133.9352
    10  132.9791   132.9831   133.0219
    % of descent done by J=3:  97.6 %     93.1 %     89.3 %

Three steps, one plateau. Halving the step twice moves the stall by 0.04 out of
the 18.8 that separates it from the exact convex optimum, and every step still
converges within about three iterations. The plateau is a property of the
method at a binding box, not of the step -- so no step-size choice makes that
baseline look like a converging method, and the figure was telling the truth.

The same sweep at ``u_max = 0.05`` reaches 79.664 at J = 10 against the 79.599
that `box_binding.py` predicted for that box -- 0.08 % apart, which is the
instrument checking itself against a number already on file.

**One consequence worth having.** If the contender displayed as *Standard-PGD*
should carry the standard step, ``1/L`` is affordable: the two differ by 0.057
at J = 4 and by 0.004 at J = 10. That is a labelling decision with a measured
cost rather than an assumed one -- but it buys no visual improvement, which was
the reason it was proposed.

**Tier caveat, learned the hard way.** ``--tier standard`` overrides
``training.seeds`` to 1 and ``evaluation.protocol.n_batches`` to 4. For a fixed
contender the seed count is irrelevant -- its across-seed spread is exactly
0.0000 on the record -- but the batch count is not: the control arm reads
132.9791 where the publication record reads 133.0119. Every comparison a run of
this probe makes is within its own arms and none may be set beside a
publication number.

Usage::

    uv run python tools/probes/pgd_step_sweep.py \\
        studies/icassp_exact_convex/fig5_stress_depth.toml \\
        --fractions 2,1,0.5 --depths 10

Read beside `box_binding.py`, whose analytic PGD column this extends into the
depth axis.
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import tomllib
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]

#: The frozen n = 100 plant's 1/L, authored by `tools/report_pgd_step.py`.
#: Fractions of it are exact in binary64 when they are powers of two, which is
#: why the sweep is expressed as a multiplier rather than as pasted literals.
INVERSE_LIPSCHITZ = 0.0007211432883152146


def _label(fraction: float) -> str:
    return "pgd_" + f"{fraction:g}".replace(".", "p") + "L"


def _document(source: Path, fractions: list[float], depths: list[int]) -> str:
    declared = tomllib.loads(source.read_text(encoding="utf-8"))
    lines = [
        "# GENERATED by tools/probes/pgd_step_sweep.py -- not a tracked study.",
        f"# Source: {source.name}",
        'id = "probe/pgd_step_sweep"',
        "",
        "[problem]",
        f'path = "{Path(declared["problem"]["path"]).name}"',
        "",
    ]
    for section in ("compute", "training", "evaluation"):
        lines.append(_render(section, declared[section]))
    labels = []
    for fraction in fractions:
        label = _label(fraction)
        labels.append(label)
        step = fraction * INVERSE_LIPSCHITZ
        lines += [
            "[[contenders]]",
            f'label = "{label}"',
            f"display = 'PGD (${fraction:g}/L$)'",
            'family = "unfolded_fixed"',
            'role = "baseline"',
            "",
            "[contenders.config]",
            f"num_iterations = {depths[0]}",
            f"step_size_init = {step!r}",
            "step_size_max = 1.0",
            f"horizon = {declared['contenders'][0].get('config', {}).get('horizon', 100)}",
            'init_method = "cold"',
            "",
        ]
    lines += [
        "[[sweep]]",
        'path = "contenders.*.config.num_iterations"',
        f"values = {json.dumps(depths)}",
        f"applies_to = {json.dumps(labels)}",
        "",
        "[[analyses]]",
        'id = "pgd_by_depth"',
        'kind = "cost_vs_axis"',
        'axis_path = "contenders.*.config.num_iterations"',
        "",
    ]
    return "\n".join(lines) + "\n"


def _render(header: str, table: dict[str, object]) -> str:
    lines = [f"[{header}]"]
    for key, value in table.items():
        if not isinstance(value, dict):
            lines.append(f"{key} = {json.dumps(value)}")
    for key, value in table.items():
        if isinstance(value, dict):
            lines.append("")
            lines.append(_render(f"{header}.{key}", value))
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("study", type=Path)
    parser.add_argument("--fractions", default="2,1,0.5", help="multipliers of 1/L")
    parser.add_argument("--depths", default="1,2,3,4,5,6,7,8,9,10")
    parser.add_argument("--tier", default="standard")
    parser.add_argument("--into", type=Path, default=None)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    fractions = [float(v) for v in args.fractions.split(",")]
    depths = [int(v) for v in args.depths.split(",")]
    root = args.into or Path("/tmp") / "mbl-probe-pgd"
    root.mkdir(parents=True, exist_ok=True)

    source = args.study.resolve()
    declared = tomllib.loads(source.read_text(encoding="utf-8"))
    plant = (source.parent / declared["problem"]["path"]).resolve()
    shutil.copy2(plant, root / plant.name)
    document = root / "pgd_step_sweep.toml"
    document.write_text(_document(source, fractions, depths), "utf-8")

    print(f"probe document : {document}")
    print(f"steps swept    : {[f'{f:g}/L' for f in fractions]}")
    print(f"1/L            : {INVERSE_LIPSCHITZ!r}")
    print("the incumbent step is swept as the control arm, never assumed")
    print("NOTE: --tier standard uses 1 seed and 4 evaluation batches; these")
    print("      numbers may not be set beside a publication table.\n")

    command = [
        "uv",
        "run",
        "mbl",
        "--store",
        str(root / "store"),
        "run",
        str(document),
        "--tier",
        args.tier,
    ]
    if args.dry_run:
        command.append("--dry-run")
    completed = subprocess.run(command, cwd=REPO, check=False)
    if completed.returncode or args.dry_run:
        return completed.returncode
    return subprocess.run(
        [
            "uv",
            "run",
            "mbl",
            "--store",
            str(root / "store"),
            "analyse",
            str(document),
            "--tier",
            args.tier,
        ],
        cwd=REPO,
        check=False,
    ).returncode


if __name__ == "__main__":
    sys.exit(main())
