"""Acceptance tests for the training world (Annex 01 §2.3.5, D25).

Written before the run. `TrainingSpec.problem` is the plant the training
trajectories are generated by, distinct from the plant the contender is told.
The proof of the unweld is three-way distinctness on one shared evaluation:
(model A, world A) ≠ (model A, world A′) ≠ (model A′, world A′) — if the
middle study equalled the first, the world never reached the rollout; if it
equalled the third, the contender's internals followed the world.
"""

from __future__ import annotations

import importlib
from pathlib import Path

import pytest

from mbl.experiments import DEFAULT_SPEC_BINDINGS
from mbl.runner.producer import RunReport, run_study
from mbl.spec.errors import SpecificationError
from mbl.spec.loader import load_study

_producer = importlib.import_module("tests.runner.test_producer")

NOMINAL_SEED, SHIFTED_SEED = 0, 1

#: The axis form of the declaration: scoped to the trainable contender, so
#: the analytic baseline keeps its matched training and its ModelID.
WORLD_AXIS = (
    "\n[[sweep]]\n"
    'path = "training.problem"\n'
    'values = ["rotated.npz"]\n'
    'applies_to = ["unfolded_a"]\n'
)


def _document(
    directory: Path,
    name: str = "study.toml",
    *,
    problem_seed: int = NOMINAL_SEED,
    evaluation_lines: str = "",
    training_lines: str = "",
    appendix: str = "",
) -> Path:
    directory.mkdir(parents=True, exist_ok=True)
    _producer._problem_file(directory, "problem.npz", seed=problem_seed)
    _producer._problem_file(directory, "rotated.npz", seed=SHIFTED_SEED)
    text = _producer.STUDY.format(**_producer.DEFAULTS)
    if evaluation_lines:
        marker = "[evaluation]\n"
        assert marker in text, "the producer fixture's evaluation table moved"
        text = text.replace(marker, f"{marker}{evaluation_lines}\n", 1)
    if training_lines:
        marker = "[training.data]"
        assert marker in text, "the producer fixture's training table moved"
        text = text.replace(marker, f"{training_lines}\n\n{marker}", 1)
    path = directory / name
    path.write_text(text + appendix)
    return path


def _run(document: Path, store: Path) -> RunReport:
    study = load_study(document, bindings=DEFAULT_SPEC_BINDINGS).study
    return run_study(study, store=store, bindings=DEFAULT_SPEC_BINDINGS)


def _unfolded(report: RunReport) -> dict[tuple[str, int], dict[str, float]]:
    picked = {}
    for outcome in report.outcomes:
        if outcome.label == "unfolded_a":
            picked[(str(outcome.model_id), outcome.seed)] = dict(outcome.metrics)
    assert picked
    return picked


class TestTheUnweld:
    def test_three_worlds_are_three_different_trainings(self, tmp_path: Path) -> None:
        """All three studies are scored on the SAME shifted plant, so every
        metric difference is a weight difference. Matched (A, A), unwelded
        (A, A′) and native (A′, A′) must be pairwise distinct — the first
        equality would mean the world never reached the rollout, the second
        that the contender's internals followed it."""
        shifted_eval = 'problem = { path = "rotated.npz" }'
        matched = _run(
            _document(tmp_path / "matched", evaluation_lines=shifted_eval),
            tmp_path / "store_matched",
        )
        unwelded = _run(
            _document(
                tmp_path / "unwelded",
                evaluation_lines=shifted_eval,
                appendix=WORLD_AXIS,
            ),
            tmp_path / "store_unwelded",
        )
        native = _run(
            _document(tmp_path / "native", problem_seed=SHIFTED_SEED),
            tmp_path / "store_native",
        )

        def values(report: RunReport) -> list[dict[str, float]]:
            return [m for _, m in sorted(_unfolded(report).items(), key=str)]

        assert values(matched) != values(unwelded)
        assert values(unwelded) != values(native)
        assert values(matched) != values(native)

    def test_the_axis_form_moves_only_the_scoped_contenders_model_ids(
        self, tmp_path: Path
    ) -> None:
        """Model-level for the contenders it names, invisible to the rest:
        the analytic baseline keeps its matched ModelIDs, so nothing already
        stored is orphaned by scoping the world away from it."""
        base = load_study(
            _document(tmp_path / "base"), bindings=DEFAULT_SPEC_BINDINGS
        ).study
        world = load_study(
            _document(tmp_path / "world", appendix=WORLD_AXIS),
            bindings=DEFAULT_SPEC_BINDINGS,
        ).study

        def ids(study, label):
            return {
                str(p.model_id)
                for p in study.materialise()
                if p.contender.resolved_label == label
            }

        assert ids(base, "unfolded_a").isdisjoint(ids(world, "unfolded_a"))
        assert ids(base, "baseline") == ids(world, "baseline")

    def test_a_blind_training_signature_has_no_problem_key(
        self, tmp_path: Path
    ) -> None:
        """The conditional extension law, asserted on the exact key set: a
        study without the field signs byte-identically to one predating it."""
        study = load_study(
            _document(tmp_path / "doc"), bindings=DEFAULT_SPEC_BINDINGS
        ).study
        assert set(study.training.get_signature()) == {
            "type",
            "data",
            "batch",
            "seeds",
        }


class TestTheMatchedCaseSentinel:
    """Annex 01 §2.3.5: `""` on a training.problem axis writes the absence."""

    def test_the_empty_string_position_is_the_matched_models_bit_for_bit(
        self, tmp_path: Path
    ) -> None:
        base = load_study(
            _document(tmp_path / "base"), bindings=DEFAULT_SPEC_BINDINGS
        ).study
        swept = load_study(
            _document(
                tmp_path / "swept",
                appendix=(
                    "\n[[sweep]]\n"
                    'path = "training.problem"\n'
                    'values = ["", "rotated.npz"]\n'
                    'applies_to = ["unfolded_a"]\n'
                ),
            ),
            bindings=DEFAULT_SPEC_BINDINGS,
        ).study

        def ids(study, *, world) -> set[str]:
            return {
                str(p.model_id)
                for p in study.materialise()
                if p.contender.resolved_label == "unfolded_a"
                and (p.training.problem is not None) is world
            }

        matched, shifted = ids(swept, world=False), ids(swept, world=True)
        assert matched == ids(base, world=False)
        assert matched.isdisjoint(shifted)

    def test_the_sentinel_is_refused_on_the_other_whole_spec_paths(
        self, tmp_path: Path
    ) -> None:
        with pytest.raises(SpecificationError, match="training.problem"):
            load_study(
                _document(
                    tmp_path / "doc",
                    appendix=(
                        "\n[[sweep]]\n"
                        'path = "evaluation.problem"\n'
                        'values = ["", "rotated.npz"]\n'
                        'labels = ["a", "b"]\n'
                    ),
                ),
                bindings=DEFAULT_SPEC_BINDINGS,
            )

    def test_an_axis_world_equal_to_the_told_plant_is_refused_naming_the_spelling(
        self, tmp_path: Path
    ) -> None:
        study = load_study(
            _document(
                tmp_path / "doc",
                appendix=(
                    "\n[[sweep]]\n"
                    'path = "training.problem"\n'
                    'values = ["problem.npz"]\n'
                    'applies_to = ["unfolded_a"]\n'
                ),
            ),
            bindings=DEFAULT_SPEC_BINDINGS,
        ).study
        with pytest.raises(SpecificationError, match='""'):
            study.materialise()


class TestTheRefusals:
    def test_a_world_equal_to_the_study_problem_is_refused(
        self, tmp_path: Path
    ) -> None:
        with pytest.raises(SpecificationError, match="matched case"):
            load_study(
                _document(
                    tmp_path / "doc",
                    training_lines='[training.problem]\npath = "problem.npz"',
                ),
                bindings=DEFAULT_SPEC_BINDINGS,
            )

    def test_a_missing_world_file_is_refused_by_name(self, tmp_path: Path) -> None:
        with pytest.raises(SpecificationError, match="absent.npz"):
            load_study(
                _document(
                    tmp_path / "doc",
                    training_lines='[training.problem]\npath = "absent.npz"',
                ),
                bindings=DEFAULT_SPEC_BINDINGS,
            )

    def test_a_contender_that_trains_nothing_refuses_the_world(
        self, tmp_path: Path
    ) -> None:
        """A study-wide declaration reaches the analytic baseline, whose
        offline phase consumes no trajectories — the declaration is inert
        there and is refused at the point, naming the contender."""
        document = _document(
            tmp_path / "doc",
            training_lines='[training.problem]\npath = "rotated.npz"',
        )
        with pytest.raises(SpecificationError, match="baseline"):
            _run(document, tmp_path / "store")
